#!/bin/bash

scandir=$(pwd)
depth=4
curdepth=1

while [[ $scandir != "/" && $curdepth -lt $depth ]]
do
    if [[ -e $scandir/CMakeLists.txt ]]
    then
		if [[ -e $(dirname $scandir)/CMakeLists.txt ]]
		then
			echo "Found subdirectory at $scandir, skipping build"
		else
			echo "CMake project found at $scandir"
			if [[ ! -d "${scandir}/build" ]]
			then
				echo "Creating build folder"
				mkdir $scandir/build
			fi
			cd $scandir/build
			echo "Building..."
			cmake ..
			make -j $1
			exit 0
		fi

    elif [[ -e $scandir/Makefile ]]
    then
		if [[ -e $(dirname $scandir)/CMakeLists.txt ]]
		then
			echo "Found build folder at $scandir, skipping build"
		else
			echo "Make project found, compiling..."
			cd $scandir
			make -j $1
			exit 0
		fi

    elif [[ -e $scandir/platformio.ini ]]
	then
		echo "Found PlatformIO project, running..."
		cd $scandir
		pio run
		exit 0
	fi

    scandir=$(dirname $scandir)
    curdepth=$curdepth+1
done

echo "No compatible build system found"
exit 1
